### ISSUE TITLE
TransportQLD

### ISSUE THREAD

**Issue by isbrodie1** [Dav0815/TransportNSW#2]
Hi Dav, any thoughts of porting this to QLD also?

**Comment by Dav0815** [comment]
Do you know a data source for this ? I could look into it.

**Comment by isbrodie1** [comment]
Hi,

https://translink.com.au/about-translink/open-data

I had a look into it but its way above my coding experience.

**Comment by Dav0815** [comment]
Hi @isbrodie1 ,

it seems that Translink supplies the information as GTFS data. You should be able to utilise the following component to get your information.
https://www.home-assistant.io/components/gtfs/
